siteTitle = "簡墨"
siteDescr = "鄧駿駿之隨筆 以簡墨記錄生活 尚大道至簡 大象無形"
siteAuthor = "鄧駿駿"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/cnjdeng"
siteGithubUrl = "https://github.com/lilac"
siteEmailUrl = "cnjamesdeng#--gmail.com"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = "UA-57000079-2"

linkPrefix = ""
baseUrl = "https://blog.samemoment.com"
